{% set name = "dbt-extractor" %}
{% set version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dbt_extractor-{{ version }}.tar.gz
  sha256: d6cf08ec793b8bc2bd6e260ef818230ae68a4f71436fa489f08d7db1a52e2ffe

build:
  skip: true  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - maturin
  host:
    - maturin
    - pip
    - python
  run:
    - python

test:
  imports:
    - dbt_extractor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/dbt-extractor/
  dev_url: https://github.com/dbt-labs/dbt-extractor
  # Check with upstream to package license file
  license_file: LICENSE
  license: Apache-2.0
  summary: Jinja value templates for dbt model files

extra:
  recipe-maintainers:
    - maresb
    - thewchan
